import {call,setKey} from './api.js';import {browserId,identify} from './identity.js';import {loadPicklists,picklists,bindAddable} from './picklists.js';import {load as loadReferrals,getRows,initFilters,bindForm} from './referrals.js';import {loadIntake,bindIntake} from './intake.js';import {loadSources,bindSources,loadLmn,bindLmn,renderUsers} from './admin.js';
const $=x=>document.getElementById(x);
async function refreshAll(){const rows=await loadReferrals();await loadIntake(rows);const open=(await call('intake-list')).filter(x=>!['Archived','Matched'].includes(x.review_status)).length;$('intakeCount').textContent=String(open);$('intakeOpenCount').textContent=String(open)}
async function start(){await loadPicklists();initFilters();for(const [id,field] of [['patient','patient'],['fowner','owner'],['provider','provider'],['payer','payer'],['dx','dx'],['next','next_action']])await bindAddable($(id),field);bindForm();bindIntake();bindSources();bindLmn();const me=await identify();$('userId').textContent=browserId();$('staffName').textContent=me.staffName?' · '+me.staffName:'';await refreshAll()}
$('login').onsubmit=async e=>{e.preventDefault();$('msg').textContent='';setKey($('pw').value);try{await call('auth');sessionStorage.setItem('phv5',$('pw').value);$('gate').style.display='none';$('app').hidden=false;await start()}catch(err){$('msg').textContent=err.message||'Connection failed'}};
document.querySelectorAll('.tab').forEach(t=>t.onclick=async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(t.dataset.view).classList.add('active');if(t.dataset.view==='usersView')await renderUsers();if(t.dataset.view==='intakeView')await loadIntake(getRows())});
document.addEventListener('referral-opened',async e=>{await Promise.all([loadSources(e.detail.referral),loadLmn(e.detail.referral)])});
document.addEventListener('referrals-changed',async()=>{await refreshAll()});
const saved=sessionStorage.getItem('phv5');if(saved){setKey(saved);call('auth').then(async()=>{$('gate').style.display='none';$('app').hidden=false;await start()}).catch(()=>sessionStorage.removeItem('phv5'))}
