import {call} from './api.js';
import {browserId} from './identity.js';
import {picklists,fillSelect,bindAddable} from './picklists.js';
import {clinics,stages,auths,lmns} from './referrals.js';
const $=x=>document.getElementById(x);const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));let intake=[];let referrals=[];let enhanced=false;
function upgradeEditor(){if(enhanced)return;enhanced=true;
  for(const [id,field] of [['intakePatient','patient'],['intakePayer','payer'],['intakeProvider','provider'],['intakeDx','dx']]){const old=$(id);const sel=document.createElement('select');sel.id=id;sel.className='field';old.replaceWith(sel);bindAddable(sel,field)}
  const disposition=$('intakeMatchReferral').closest('section');const section=document.createElement('section');section.innerHTML=`<h3>Referral Workflow</h3><div class="grid">
    <label>Clinic<select id="intakeClinic" class="field"></select></label><label>Owner<select id="intakeOwner" class="field"></select></label>
    <label>Referral Received Date<input id="intakeReferralReceivedDate" type="date" class="field"></label><label>Email Received Date<input id="intakeEmailReceivedDate" type="date" class="field"></label>
    <label>LMN Status<select id="intakeLmnStatus" class="field"></select></label><label>Stage<select id="intakeStage" class="field"></select></label>
    <label>Authorization Status<select id="intakeAuth" class="field"></select></label><label>Auth Submitted<input id="intakeAuthSubmitted" type="date" class="field"></label>
    <label>Auth Decision<input id="intakeAuthDecision" type="date" class="field"></label><label>Authorization #<input id="intakeAuthNum" class="field"></label>
    <label>Authorized Visits<input id="intakeVisits" type="number" class="field"></label><label>Scheduled Start<input id="intakeScheduled" type="date" class="field"></label>
    <label>First Treatment<input id="intakeStarted" type="date" class="field"></label><label>Due<input id="intakeDue" type="date" class="field"></label>
    <label>Priority<select id="intakePriority" class="field"><option>Normal</option><option>High</option><option>Urgent</option></select></label>
    <label class="wide">Next Action<select id="intakeNext" class="field"></select></label>
    <label class="wide">Notes<textarea id="intakeNotes" rows="4" class="field"></textarea></label>
  </div>`;disposition.parentNode.insertBefore(section,disposition);bindAddable($('intakeOwner'),'owner');bindAddable($('intakeNext'),'next_action')}
function fillWorkflow(x={}){fillSelect($('intakePatient'),picklists.patient||[],{addable:true,current:x.patient_name||''});fillSelect($('intakePayer'),picklists.payer||[],{addable:true,current:x.payer||''});fillSelect($('intakeProvider'),picklists.provider||[],{addable:true,current:x.provider||''});fillSelect($('intakeDx'),picklists.dx||[],{addable:true,current:x.diagnosis||''});fillSelect($('intakeOwner'),picklists.owner||[],{addable:true,current:x.owner||'Unassigned'});fillSelect($('intakeNext'),picklists.next_action||[],{addable:true,current:x.next_action||'Review incoming referral'});fillSelect($('intakeClinic'),clinics,{blank:'Select clinic',current:x.clinic||''});fillSelect($('intakeStage'),stages,{blank:null,current:x.stage||'Referral Received'});fillSelect($('intakeAuth'),auths,{blank:null,current:x.auth||'Not Started'});fillSelect($('intakeLmnStatus'),lmns,{blank:null,current:x.lmn_status||'Not Started'})}
export async function loadIntake(referralRows=[]){referrals=referralRows;intake=await call('intake-list');renderIntake();return intake}
export function renderIntake(){const q=($('intakeSearch')?.value||'').toLowerCase();const rows=intake.filter(x=>!q||[x.patient_name,x.provider,x.payer,x.diagnosis,x.sender,x.subject,x.attachment_name,x.owner,x.next_action].join(' ').toLowerCase().includes(q));$('intakeCount').textContent=String(intake.filter(x=>x.review_status!=='Archived'&&x.review_status!=='Matched').length);$('intakeRows').innerHTML=rows.map(x=>`<tr><td>${esc(new Date(x.received_at).toLocaleDateString())}</td><td>${esc(x.source_type)}</td><td><b>${esc(x.patient_name||'Needs review')}</b><div class="small">${esc(x.attachment_name||x.subject||'')}</div></td><td>${esc(x.provider||'')}</td><td>${esc(x.payer||'')}</td><td>${esc(x.diagnosis||'')}</td><td><span class="pill">${esc(x.review_status)}</span></td><td><button class="btn intakeOpen" data-id="${x.id}">Open</button></td></tr>`).join('');document.querySelectorAll('.intakeOpen').forEach(b=>b.onclick=()=>openIntake(b.dataset.id))}
function openIntake(id){upgradeEditor();const x=intake.find(r=>r.id===id);if(!x)return;$('intakeId').value=x.id;$('intakeSourceType').value=x.source_type||'Email';$('intakeSourceAccount').value=x.source_account||'';$('intakeSender').value=x.sender||'';$('intakeSubject').value=x.subject||'';$('intakeAttachment').value=x.attachment_name||'';$('intakeSourceUrl').value=x.source_url||x.attachment_url||'';fillWorkflow(x);$('intakeDob').value=x.dob||'';$('intakeEmail').value=x.patient_email||'';$('intakePhone').value=x.patient_phone||'';$('intakeConfidence').value=x.extraction_confidence??'';$('intakeStatus').value=x.review_status||'Needs Review';$('intakeRawText').value=x.raw_text||'';const d=String(x.received_at||'').slice(0,10);$('intakeReferralReceivedDate').value=x.referral_received_date||d;$('intakeEmailReceivedDate').value=x.email_received_date||d;$('intakeAuthSubmitted').value=x.auth_submitted||'';$('intakeAuthDecision').value=x.auth_decision||'';$('intakeAuthNum').value=x.auth_num||'';$('intakeVisits').value=x.visits??'';$('intakeScheduled').value=x.scheduled||'';$('intakeStarted').value=x.started||'';$('intakeDue').value=x.due||'';$('intakePriority').value=x.priority||'Normal';$('intakeNotes').value=x.notes||'';$('intakeMatchReferral').innerHTML='<option value="">Select existing referral…</option>'+referrals.map(r=>`<option value="${r.id}">${esc(r.referralCode||'')} — ${esc(r.patient)}</option>`).join('');$('intakeDrawer').classList.add('open')}
function payload(){return {id:$('intakeId').value||'',sourceType:$('intakeSourceType').value,sourceAccount:$('intakeSourceAccount').value,sender:$('intakeSender').value,subject:$('intakeSubject').value,attachmentName:$('intakeAttachment').value,sourceUrl:$('intakeSourceUrl').value,patientName:$('intakePatient').value,dob:$('intakeDob').value,payer:$('intakePayer').value,provider:$('intakeProvider').value,diagnosis:$('intakeDx').value,patientEmail:$('intakeEmail').value,patientPhone:$('intakePhone').value,extractionConfidence:$('intakeConfidence').value,reviewStatus:$('intakeStatus').value,rawText:$('intakeRawText').value,clinic:$('intakeClinic').value,owner:$('intakeOwner').value,referralReceivedDate:$('intakeReferralReceivedDate').value,emailReceivedDate:$('intakeEmailReceivedDate').value,lmnStatus:$('intakeLmnStatus').value,stage:$('intakeStage').value,auth:$('intakeAuth').value,authSubmitted:$('intakeAuthSubmitted').value,authDecision:$('intakeAuthDecision').value,authNum:$('intakeAuthNum').value,visits:$('intakeVisits').value,scheduled:$('intakeScheduled').value,started:$('intakeStarted').value,nextAction:$('intakeNext').value,due:$('intakeDue').value,priority:$('intakePriority').value,notes:$('intakeNotes').value,browserId:browserId()}}
async function saveCurrent(){const p=payload();const saved=await call('intake-save',{payload:JSON.stringify(p)});$('intakeId').value=saved.id;return saved}
export function bindIntake(){upgradeEditor();if($('intakeSearch'))$('intakeSearch').oninput=renderIntake;$('newIntake').onclick=()=>{['intakeId','intakeSourceAccount','intakeSender','intakeSubject','intakeAttachment','intakeSourceUrl','intakeDob','intakeEmail','intakePhone','intakeConfidence','intakeRawText','intakeAuthSubmitted','intakeAuthDecision','intakeAuthNum','intakeVisits','intakeScheduled','intakeStarted','intakeDue','intakeNotes'].forEach(id=>$(id).value='');fillWorkflow({});$('intakeSourceType').value='Email';$('intakeStatus').value='Needs Review';const d=new Date().toISOString().slice(0,10);$('intakeReferralReceivedDate').value=d;$('intakeEmailReceivedDate').value=d;$('intakePriority').value='Normal';$('intakeMatchReferral').innerHTML='<option value="">Select existing referral…</option>'+referrals.map(r=>`<option value="${r.id}">${esc(r.referralCode||'')} — ${esc(r.patient)}</option>`).join('');$('intakeDrawer').classList.add('open')};$('closeIntake').onclick=()=>$('intakeDrawer').classList.remove('open');$('intakeForm').onsubmit=async e=>{e.preventDefault();await saveCurrent();$('intakeDrawer').classList.remove('open');await loadIntake(referrals)};$('createReferralFromIntake').onclick=async()=>{await saveCurrent();const id=$('intakeId').value;if(!id)return;await call('intake-create-referral',{id,browserId:browserId()});$('intakeDrawer').classList.remove('open');document.dispatchEvent(new CustomEvent('referrals-changed'))};$('matchIntake').onclick=async()=>{await saveCurrent();const id=$('intakeId').value,referralId=$('intakeMatchReferral').value;if(!id||!referralId)return;await call('intake-match',{id,referralId,browserId:browserId()});$('intakeDrawer').classList.remove('open');document.dispatchEvent(new CustomEvent('referrals-changed'))};$('archiveIntake').onclick=async()=>{const id=$('intakeId').value;if(!id)return;await call('intake-archive',{id});$('intakeDrawer').classList.remove('open');await loadIntake(referrals)}}
